### ISSUE TITLE
v1 todo

### ISSUE THREAD

**Issue by enceladus** [thencc/Irulan#1]
**Setup**
- [x] WalletConnect integration
- [x] Custom header in node config

**Browser**
- [x] Search for accounts, apps, and assets
- [x] Format response depending on type
- [x] Clicking on accounts & assets elsewhere in Irulan loads them in the browser
- [ ] Get Local State panel
- [x] Generate Algonaut.js code for searches

**Contract Tool**
- [x] Call app
- [x] Opt-in
- [x] Delete app
- [x] Close out of app
- [x] Deploy compiled contract
- [x] Update contract
- [x] Show + copy Algonaut.js code

**Asset Management**
_Not sure if we should be worrying about this right now..._
